Add pycgmes-shacl as distribution package

diff --git a/.github/workflows/_core.yaml b/.github/workflows/_core.yaml
--- a/.github/workflows/_core.yaml
+++ b/.github/workflows/_core.yaml
@@ -103,11 +103,19 @@ jobs:
         if: ${{ ! inputs._SKIP_QUALITY }}
         run: poetry run scons coverage
 
-      - name: poetry build
+      - name: poetry build pycgmes
         run: poetry build
 
-      - name: poetry publish
+      - name: poetry build pycgmes-shacl
+        run: |
+          cd SHACL
+          poetry build
+
+      # PUBLISH NOTE: see comments in the catch step.
+      - name: poetry publish pycgmes
         if: ${{ inputs.deploy }}
+        continue-on-error: true
+        id: pycgmes-publish
         env:
           UNO_NEXUS_PASSWORD: ${{ secrets.UNO_NEXUS_PASSWORD }}
           UNO_NEXUS_USER: ${{ secrets.UNO_NEXUS_USER }}
@@ -115,3 +123,33 @@ jobs:
           poetry config repositories.internal-uno https://nexus.appx.cloud/repository/uno-pypi/
           poetry config http-basic.internal-uno "$UNO_NEXUS_USER" "$UNO_NEXUS_PASSWORD"
           poetry publish --repository internal-uno
+
+      - name: poetry publish pycgmes-shacl
+        if: ${{ inputs.deploy }}
+        id: pycgmes-shacl-publish
+        continue-on-error: true
+        env:
+          UNO_NEXUS_PASSWORD: ${{ secrets.UNO_NEXUS_PASSWORD }}
+          UNO_NEXUS_USER: ${{ secrets.UNO_NEXUS_USER }}
+        run: |
+          # Config done in previous step
+          cd SHACL
+          poetry publish --repository internal-uno
+
+      - name: catch publish error
+        if: ${{ inputs.deploy }}
+        # It is valid to only have pycgtmes published, only pycgmes-shacl, ot both.
+        # it is tricky to know when which one should be done, so none of them fails,
+        # but this next step look at the outcome of the 2 publish steps and decide if
+        # something was wrong.
+        # Note: use outcome, not conclusion, because of continue-on-error
+        # see https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context
+        run: |
+          pycgmes="${{ steps.pycgmes-publish.outcome }}"
+          shacl="${{ steps.pycgmes-shacl-publish.outcome }}"
+          if [[ "$pycgmes" == 'failure' && "$shacl" == 'failure' ]]; then
+            echo "Both publish steps failed. This is not correct."
+            exit 1
+          else
+            echo "At least one publish step succeeded (pycgmes="$pycgmes", pycgmes-shacl="$shacl"). Good enough."
+          fi
